version: '3'
services:
  postgres:
    container_name: daily-report
    image: postgres:14.2-alpine
    ports:
      - 4432:5432
    volumes:
      - ./db/init.d:/docker-entrypoint-initdb.d
      - ./db/data:/var/lib/postgresql/data
    environment:
      POSTGRES_INITDB_ARGS: --encoding=UTF-8
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    hostname: postgres
    user: root
    restart: always
